config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    # Redirests signing out users back to sign-in
    get "users", to: "devise/sessions#new"
  end
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  # Defines the root path route ("/")
  root "gift_exchanges#index"

  resources :gift_exchanges
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/gift_exchange.rb
class GiftExchange < ApplicationRecord
  belongs_to :owner, class_name: 'User'
  has_and_belongs_to_many :participants,
                          class_name: 'User',
                          join_table: :gift_exchange_users,
                          foreign_key: :gift_exchange_id,
                          association_foreign_key: :participant_id
  validates_presence_of :name, :owner, :event_date
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates_presence_of :first_name, :last_name, :email
  has_many :managed_gift_exchanges, class_name: GiftExchange.name, foreign_key: :owner_id
  has_and_belongs_to_many :participatory_gift_exchanges,
                          class_name: GiftExchange.name,
                          join_table: :gift_exchange_users,
                          foreign_key: :participant_id,
                          association_foreign_key: :gift_exchange_id

end

app/models/wish_list.rb
class WishList < ApplicationRecord
  belongs_to :participant, class_name: 'User'
  belongs_to :gift_exchange
  validates_presence_of :participant, :gift_exchange
  validates_uniqueness_of :participant_id, scope: :gift_exchange_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end
end

app/controllers/gift_exchanges_controller.rb
class GiftExchangesController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @gift_exchanges = current_user.managed_gift_exchanges
  end

  def show
    @gift_exchange = GiftExchange.find(params[:id])
  end

  def new
    @gift_exchange = GiftExchange.new
  end

  def create
    @gift_exchange = GiftExchange.new(**gift_exchange_params, owner: current_user)
    if @gift_exchange.save
      redirect_to gift_exchanges_path, notice: 'Gift exchange was successfully created.'
    else
      render :new
    end
  end

  def edit
    unless current_user.managed_gift_exchanges.exists?(params[:id])
      redirect_to gift_exchanges_path, notice: 'You are not authorized.'
      return
    end

    @gift_exchange = GiftExchange.find(params[:id])
  end

  def update
    @gift_exchange = GiftExchange.find(params[:id])
    if @gift_exchange.update(gift_exchange_params)
      redirect_to gift_exchanges_path, notice: 'Gift exchange was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @gift_exchange = GiftExchange.find(params[:id])
    @gift_exchange.destroy
    redirect_to gift_exchanges_path
  end

  private

  def gift_exchange_params
    params.require(:gift_exchange).permit(:name, :description, :event_date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gift_exchanges_helper.rb
module GiftExchangesHelper
end

app/views/gift_exchanges/_form.html.erb
<%= form_for @gift_exchange, data: {turbo_frame: "_top"} do |f| %>
  <div class="container-fluid">
    <div class="row m-3">
      <div class="col form-label">
        <%= f.label :event_date %>
      </div>
      <div class="col form-control">
        <%= f.text_field :event_date, data: { controller: 'date' } %>
      </div>
    </div>
    <div class="row m-3">
      <div class="col form-label">
        <%= f.label :name %>
      </div>
      <div class="col form-control">
        <%= f.text_field :name %>
      </div>
    </div>
    <div class="row m-3">
      <div class="col form-label">
        <%= f.label :description %>
      </div>
      <div class="col form-control">
        <%= f.text_area :description %>
      </div>
    </div>
    <%= f.submit %>
  </div>
<% end %>

app/views/gift_exchanges/edit.html.erb
<h1>Edit Gift Exchange Event</h1>
<%= render 'form' %>

app/views/gift_exchanges/index.html.erb
<h1>Gift Exchanges</h1>
<div class="container-fluid">
  <div class="row m-3">
    <div class="col">
      <% if @gift_exchanges.empty? %>
        <p>There are no gift exchanges yet. Create one <%= link_to 'here', new_gift_exchange_path %></p>
      <% else %>
        <%= link_to "Create", new_gift_exchange_path %> new gift exchange
      <% end %>
    </div>
  </div>
  <% @gift_exchanges.each do |exchange| %>
    <div class="row m-3">
      <div class="col">
        <%= link_to exchange.name, gift_exchange_path(exchange) %>
      </div>
      <div class="col">
        <%= exchange.event_date.strftime("%B %d, %Y") %>
      </div>

      <% if exchange.owner == current_user %>
        <div class="col d-flex flex-row justify-content-between align-content-center">
          <%= link_to "Edit", edit_gift_exchange_path(exchange), class: 'btn btn-primary' %>
          <%= button_to "Delete",
                        gift_exchange_path(exchange),
                        method: :delete,
                        class: 'btn btn-danger',
                        data: { confirm: "Are you sure?" } %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/gift_exchanges/new.html.erb
<h1>New Gift Exchange Event</h1>
<%= render 'form' %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid d-flex flex-row justify-content-end">
    <button class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent"
            aria-expanded="false"
            aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Account", edit_user_registration_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= button_to "Logout", destroy_user_session_path, method: :delete, class: 'nav-link' %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: 'nav-link' %>
          </li>
        <% end %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimplifiedGiving</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= render "layouts/navbar" %>
    <%= yield %>
  </body>
</html>